language: python

python:
  - "3.4"

env:
  global:
    - WDR_LOGGING_LOGLEVEL=ERROR
    - WDR_LOGGING_LOGFILE=/tmp/woudc-data-registry.log
    - WDR_DB_DEBUG=False
    - WDR_DB_TYPE=postgresql
    - WDR_DB_HOST=localhost
    - WDR_DB_PORT=5432
    - WDR_DB_NAME=woudc-data-registry
    - WDR_DB_USERNAME=postgres
    - WDR_DB_PASSWORD=postgres
    - PGPASSWORD=postgres
    - WDR_SEARCH_TYPE=elasticsearch
    - WDR_SEARCH_URL=http://localhost:9200/
    - WDR_WAF_BASEURL=https://woudc.org/archive/
    - WDR_WAF_BASEDIR=/tmp
    - WDR_TABLE_SCHEMA=data/tables_schema.json
    - WDR_TABLE_CONFIG=data/tables.yaml
    - WDR_ERROR_CONFIG=data/errors.csv

addons:
  apt:
    packages:
      - pandoc
  postgresql: "9.3"

services:
  - postgresql

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements-pg.txt
  - pip install coveralls
  - python setup.py build
  - python setup.py install

script:
  - python setup.py test
  - find . -type f -name "*.py" | xargs flake8
  - python setup.py --long-description | rst2html5.py

after_success:
  - coverage run --source=woudc_data_registry -m unittest woudc_data_registry.tests.test_data_registry
  - coverage report -m
  - coveralls
  - python setup.py bdist_wheel
  - debuild -b -uc -us
